### ISSUE TITLE
op on a vector using text

### ISSUE THREAD

**Issue by hagna** [robpike/ivy#100]
```
op pal x = t = '%d' text x; (rot t) *.== t
```

Is an attempt at palindrome, and it almost works:

```
pal 1001
1

pal 98
0
```

I expected:

```
pal 1001 1002
1 0
```

But I get

```
pal 1001 1002
0
```

The text operator seems to include spaces, so maybe that's part of the problem?

```
rho "%d" text 1 2 3
5
```

**Comment by robpike** [comment]
This is related to https://github.com/robpike/ivy/issues/69, the lack of a way to force an operator on a vector to run an element at a time.

In the meantime, you can write a recursive loop:

```
op pal x =
	(rho x) <= 1: (rot t) *.== t = '%d' text x
	(pal x[1]), pal 1 drop x


pal 1
1

pal 234
0

pal 202
1

pal 202 301
1 0

```

**Comment by hagna** [comment]
Oh nice!

Oh right @rsc mentions "tail recursion" in #69.

In light of this personal lesson and #69, I'll close.

Thanks
