### ISSUE TITLE
`)Erase` for global variables. 

### ISSUE THREAD

**Issue by mselh** [robpike/ivy#106]
with the commit, 
0290510180ee94f5732abf39074d5acf2b73432f

Am I right in thinking, this makes sense now?

![image](https://user-images.githubusercontent.com/79106885/151705436-eaab5c46-036e-42e5-bcd6-0c970721428e.png)

**Comment by robpike** [comment]
In ivy, it's sufficient to say

x = 0

to free up the variable name x and use it as an operator. Given that, I'm not sure an erase helper is necessary.
