### ISSUE TITLE
The scan operator (\) gets lost

### ISSUE THREAD

**Issue by ainar-g** [robpike/ivy#11]
OS: Android.

Input: ``+\1,2,3``.

Result: the output is correct (``1 3 6``), but the prompt looks like

    > +,2,3
    1 3 6

instead of

    > +\1,2,3
    1 3 6

It looks like something somewhere escapes the backslash and the character after it.

* * *

**EDIT:** Now that I think of it, shouldn't this issue really be an issue on the github.com/golang/go tracker?

**Comment by robpike** [comment]
This is a bug in the android wrapper. I will forward it to the authors of that program.
