### ISSUE TITLE
multi-dimensional indexing question

### ISSUE THREAD

**Issue by rsc** [robpike/ivy#111]
_Originally posted by @fumin in https://github.com/robpike/ivy/issues/28#issuecomment-1120686350_:

Why does `(5 5 rho iota 25)[3 2; 1 2 3]` return the following?

```
11 12
13  6
 7  8
```

I was expecting

```
11 12 13 
6 7  8
```

which is also what's returned by https://tryapl.org/ with the expression `(5 5 ⍴ ⍳ 25)[3 2; 1 2 3]`.

<details>
  <summary>Below is my investigation</summary>  

```
(5 5 rho iota 25)[3 2; 1]
11 6

(5 5 rho iota 25)[3 2; 1 2]
11 12
 6  7

(5 5 rho iota 25)[3 2; 1 2 3]
11 12
13  6
 7  8
```
</details>

**Comment by rsc** [comment]
Definitely a bug. Will look into a fix.

**Comment by rsc** [comment]
Sent #112 with a fix.

**Comment by fumin** [comment]
Thanks @rsc , I confirm #112 works for all the variants I can think of.
It's also good to see the internals of ivy in this change in action, enlightening! : )
