### ISSUE TITLE
iOS app fails to open, missing from the app store.

### ISSUE THREAD

**Issue by tavi-vi** [robpike/ivy#115]
The iOS app seems to not work anymore, it simply fails to open. I recently updated to iOS 16.0, but that could just be coincidental timing. It seems to be missing from the app store as well.

**Comment by robpike** [comment]
Yes, it's been removed. It wasn't practical to update it for Google's iOS guidelines. I am considering relaunching it privately, but of course it remains available as a Unix program.

**Comment by tavi-vi** [comment]
I appreciate the clarification!

**Comment by robpike** [comment]
You can also build and install it on your device yourself, as I have done.
