### ISSUE TITLE
Where to as questions about Ivy ?

### ISSUE THREAD

**Issue by kpym** [robpike/ivy#121]
Where is the place to ask (stupid) questions about Ivy ?

- on stack exchange https://stackoverflow.com/questions/tagged/ivy is about Apache Ivy,
- on reddit https://www.reddit.com/r/Ivy/ is about ... I don't know what.

Maybe opening the discussions for this project could help?

**Comment by robpike** [comment]
I read the issues, so this works, but I have opened the discussions as well.

The user community is pretty small, so don't expect much discussing. And also ivy was made as a demo of some ideas, not as a serious attempt at a full programming language. It's just not built that way.

**Comment by kpym** [comment]
Thanks !
