### ISSUE TITLE
Ivy iOS App Broken as of iOS 16 +

### ISSUE THREAD

**Issue by carlomunguia** [robpike/ivy#126]
After iOS 16 landed, Ivy no longer loads properly - it flashes the main screen & input field and promptly exits the program - hence making it unusable. 

While I know it's running an old version of Ivy, none the less it was great to experiment with it via mobile. 

FYI & thanks again for Ivy @robpike !

**Comment by dmitshur** [comment]
Issue #115 is related.

**Comment by carlomunguia** [comment]
Closing considering #115 (which is closed) - didn't realize it's been removed from App Store.
