### ISSUE TITLE
provide enclose and disclose operations

### ISSUE THREAD

**Issue by fzipp** [robpike/ivy#132]
One can implement equivalent operations to APL's monadic ⊂ and ⊃ like this:

	op enclose  a = 1 take a a
	op disclose a = a[1]

Unfortunately, the implementation of `disclose` depends on the origin.
Would it perhaps make sense to provide them as builtins?

Other names could be `box` or `nest` for enclose, and `first` for disclose.

**Comment by arl** [comment]
> Unfortunately, the implementation of disclose depends on the origin.

Isn't there a way to programmatically query whether the origin is 0 or 1 ? In which case the implementation of `disclose` could be made in pure ivy.

**Comment by robpike** [comment]
What's missing first is the equivalent of the quad "operator", and I've been thinking about a good way to provide that. I actually had a prototype working but want to proceed carefully.

**Comment by robpike** [comment]
The documentation I can find is unclear. Maybe the next round will be correct by your understanding.

**Comment by robpike** [comment]
Glad to hear it. Thanks for the bug reports.
