### ISSUE TITLE
help texts for `sys "date"` and `sys "time"` are swapped

### ISSUE THREAD

**Issue by fzipp** [robpike/ivy#133]
The help texts for `sys "date"` and `sys "time"` say:

```
"date":      the current time as a vector of numbers:
               year month day hour minute second
"time":      the current time in Unix format
```

The actual outputs are exactly the other way around:

```
sys "date"
Sun Jul 30 00:22:20 CEST 2023

sys "time"
2023 7 30 0 22 35.044431
```

**Comment by robpike** [comment]
Well that's embarrassing, but of course trivial to fix.

Having a date as a string seems helpful to me, but of course you also have the broken down time. Regardless, your suggestion of a single nanosecond counter sounds worthwhile.

**Comment by robpike** [comment]
That's too many new functions. Date formatting is a black hole. I suggest instead that
   "T" text sys "ns"
produce the Unix date format. Maybe one new function to go the other way, but I want to think about it more.

**Comment by robpike** [comment]
commit d6118f9 updates this.

**Comment by robpike** [comment]
Perhaps encode and decode with a special-purpose LHS is the way to pack and unpack a time integer.

**Comment by robpike** [comment]
I went back and forth on where to document these features, but I agree now. I will put it in both places.
I will also add sys "now" as an undocumented synonym, just for you :)
