### ISSUE TITLE
Matrix is a vector

### ISSUE THREAD

**Issue by ombreve** [robpike/ivy#161]
Hello,
I tried this (v0.3.4 installed as latest):

iota rho 1 1 1
-> matrix is vector

v = 1 1 1
iota rho v
-> matrix is vector

I would expect : 1 2 3
This used to work if I recall correctly. Maybe a regression ?

Best regards !

**Comment by robpike** [comment]
Yep, that's a bug introduced fairly recently. I have a simple fix that I will push out once I'm convinced it's the right answer.
