### ISSUE TITLE
proposal: vector arguments for functions

### ISSUE THREAD

**Issue by rsc** [robpike/ivy#175]
For complex ivy programs, having at most two arguments to a function is too limiting. For example, I implemented modular exponentiation just now, and that is fundamentally a ternary operation. The obvious answer is to make an argument a vector of arguments, and I do that, writing code like this:

```
op modexp v =
    b = v[1]
    e = v[2]
    m = v[3]
    use b e m
```

It would be nice if I could write this instead:

```
op modexp (b e m) = 
    use b e m 
```

The implementation would be that when modexp is called, ivy checks that the argument is a 3-element vector, errors out otherwise, and assigns the 3 elements to b, e, m at the start of the function. A vector could appear on the left as well, of course:

```
op (x1 y1) area (x2 y2) = abs (x1-x2)*(y1-y2)
```

I was going to suggest that this could be generalized to ordinary assignments too, making the assignment during function calls less of a special case. That is, I was going to suggest that

```
(x1 x2) = 1 2
```

be made to work too. But I hadn't realized (until I just tried it) that this form already works, as does the unparenthesized form. Making that same assignment work during function calls arguably makes the language more regular, removing a special case rather than adding one.

~~In exec.Function, Left and Right would need to change to value.Exprs, and the function parser would~~
(_Edit_: Actual description below.)

Separately, right now sliceExpr (the vector LHS form of an assignment) only allows variables to appear. I wonder if it should allow any assignable value, meaning that these would become valid:

```
(x[1] y[1]) = 1 2
(x (y z)) = 1 (2 3)
```

It looks like this would be a small change in parse.Parser.expr and then in parse.assignment to implement sliceExpr by recursing. In the case of parse.assignment, recursing could shorten the code, since it would remove the current duplication of code handling assignment to a \*variableExpr. Right now, the function invocations in exec.Function.EvalUnary/EvalBinary call c.AssignLocal with fixed variable numbers (1, 2). They would instead call parse.Assign, which would expose the new recursive implementation of parse.assignment.

**Comment by magical** [comment]
Nit: this sentence seems incomplete/truncated:

> In exec.Function, Left and Right would need to change to value.Exprs, and the function parser would

**Comment by robpike** [comment]
Actually 

`
x y = 1 2
`

works without the parens. And of course you can already give vectors to ops. So what you're asking for is some convenience and mild typechecking (vector length), right?  Seems pretty reasonable. APL was always limiting that way.

And for assignment generalization, sure, although internally that code is already bordering on too complex.

**Comment by rsc** [comment]
@magical, thanks, deleted that line. The implementation description at the bottom is the continuation of that thought.

**Comment by robpike** [comment]
Except the gerund for "recur" is "recurring". :-)

**Comment by rsc** [comment]
I've implemented this in a pair of commits, shown at the top of https://github.com/rsc/ivy/commits/master/. 
To keep things simple, I'll wait to send a PR until the commits below have merged.

**Comment by robpike** [comment]
Waiting for this PR.

**Comment by rsc** [comment]
Sent #186 to set up for it.
