### ISSUE TITLE
ivy: buggy docs for mdiv

### ISSUE THREAD

**Issue by rsc** [robpike/ivy#180]
```
% ivy
)help mdiv

Binary operators:
	Name                  APL   Ivy       Meaning
	Matrix divide         A⌹B   mdiv      Solution to system of linear equations Ax = B
	                                      For real vectors, the magnitude of A projected on B
```

Experimenting, it looks like mdiv actually solves Bx = A, not Ax = B
(and the behavior matches tryapl.org, so it's a doc bug).

**Comment by robpike** [comment]
I think you're right, both experimentally and notationally. If you think of the equation
Ax = B
then x is the solution (and the result of mdiv), and if you solve using notation rather than rigor you get
x = B mdiv A

Also unary mdiv would be nice to add - a naive implementation is easy.

**Comment by robpike** [comment]
Actually there is already inv, which should probably be renamed mdiv to avoid stealing a word, and by analogy with the division operator.

Meanwhile I notice inverse works only for 2-d matrices. I'll file an issue about that but in the meantime will at least add an error about it.
