### ISSUE TITLE
cannot get

### ISSUE THREAD

**Issue by xunshicheng** [robpike/ivy#19]
when i get the source code by the command: go get github.com/robpike/ivy
it print: can't load package: package github.com/robpike/ivy: code in directory D:\gocode\src\github.com\robpike\ivy expects import "robpike.io/ivy"

could you get me a hand！

**Comment by robpike** [comment]
See the import comment, or listen to the error message. Ivy uses a custom import.

go get robpike.io/ivy

It is a fair point though that this should be explained in the README. I will fix that.
