### ISSUE TITLE
Should floatPower be moved to the math/big package?

### ISSUE THREAD

**Issue by zboralski** [robpike/ivy#22]
@robpike we're using this function in our code now and I was wondering if it was any reason for not having it in the math/big package. Cheers :)

**Comment by robpike** [comment]
@griesemer is considering borrowing some ivy code and adapting it into math/big. Some of it will already happen in 1.6

**Comment by zboralski** [comment]
That's great :) 

We adapted some of the ivy code into our math/big fork (App Engine is still using 1.4.2, and big Floats are only available in 1.5)

**Comment by robpike** [comment]
Be aware that there are certainly better algorithms for most of the transcendentals in ivy. I wrote the obvious code using my understanding of mathematics, which is not the same as expert understanding of floating-point arithmetic.

**Comment by robpike** [comment]
Closing as not really about this program.
