### ISSUE TITLE
Inversed Residue Arguments

### ISSUE THREAD

**Issue by dim13** [robpike/ivy#26]
In contrast to all other commands, residue argument order is inconsistent with APL syntax.

I would like to propose to swap them, as it would then simplify porting of APL algorithms to Ivy.

Documentation excerpt:
```
Residue               A∣B           B modulo A
                            mod     A modulo B (Euclidean)
                            imod    A modulo B (Go)
```
Should read:
```
Residue               A∣B           B modulo A
                            mod     B modulo A (Euclidean)
                            imod    B modulo A (Go)
```

**Comment by robpike** [comment]
I thought about this when writing ivy, and although I understand the desire for compatibility with APL, ivy is really not APL in many ways, and never will be. For the particular case of modulo, it seemed to confusing to write A mod B to mean B mod A! So no, this won't happen.
