### ISSUE TITLE
Ivy seems to "crash" on latest iOS

### ISSUE THREAD

**Issue by griesemer** [robpike/ivy#29]
After updating my iPhone 5s to the latest iOS release (10.0.1, 14A403), Ivy briefly comes up but then disappears (crashes?) and I'm back at the home screen.

Double-clicking the Home button to look at all running apps shows Ivy running, with its last result showing, but clicking on it results in the same crash again.

Probably not Ivy- but x/mobile specific.

**Comment by bronze1man** [comment]
I have known ios10 and golang 1.6 is not compatible.
Golang1.7.1 and ios10 is compatible.
the ivy may need recompile with golang1.7.1

**Comment by morriswinkler** [comment]
Yep, that is right, I tested it and it works after a recompile with 1.7, would be nice if the version in the app store get's an update. 👍

**Comment by robpike** [comment]
We are working on it. It's not nearly as easy as "git push".

**Comment by robpike** [comment]
The update is in the App store .

**Comment by griesemer** [comment]
Confirming that it works on my phone. Thanks.
