### ISSUE TITLE
loop termination condition seems wrong

### ISSUE THREAD

**Issue by RaduBerinde** [robpike/ivy#31]
Unless I am missing something, the termination condition for the loop seems incorrect:

`if l.delta.Cmp(l.prevDelta) == 0`

https://github.com/robpike/ivy/blob/master/value/loop.go#L53

`delta` is the delta between the current estimate and the previous estimate
`prevDelta` is the delta between the previous estimate and the one before that

Why should we stop if the deltas are the same? If my iterative method happens to generate estimates `0, 10, 20, 30, 33, 35, 34`, why should we stop at 30?

Seems like the correct thing to check is if `delta` is 0? I am guessing that this is how this condition ends up working in practice (it detects a string of 0s), as it's highly unlikely to actually see a string of equal but non-zero deltas.

@robpike @mjibson

**Comment by robpike** [comment]
Since the items are all Taylor series, it seems that a delta of zero is good, since the series are strictly convergent. Due to numerical issues, the delta might be very small but not zero; once it stops changing, it's time to stop the loop.

That's the idea, found empirically. I suppose a comment would help.

If you like, try your method and see if it works. Maybe it does now; there's been a lot of change since that code was written.

**Comment by RaduBerinde** [comment]
Thanks Rob - I am still struggling with why seeing the same delta between consecutive estimates is the relevant condition. Why is it time to stop the loop if the delta isn't changing (again, consider the example `0, 10, 20, 30, 33, 35, 34`)? If the delta was the difference between the estimate and some *fixed* "target" value, this would absolutely make sense, but this is not what is happening.

A non-zero delta means that the estimate is changing; so the next computation in the series will be different, so unlikely to yield the same delta. Is the idea that the estimate might "wiggle" by `+/-eps`  , where `eps` is the smallest number that can be represented with the precision we are using, or something to that effect?

Even if consecutive delta equality is indeed the condition that we want, I think we should still check that the delta itself is small (it would be better than the `l.stallCount > 3` hack..)

**Comment by robpike** [comment]
As I said, this criterion was developed empirically, and it works, empirically. Also, as I said, these are all Taylor and Maclaurin series and they are strictly convergent, so you won't see a series like the one you mentioned.

I am not a numerical expert, but I have tested this code quite thoroughly and except for some noise in the very low bits of some of the nastier trig functions, it is accurate.

However, it isn't rigorous, I know, so if you can construct a simpler test that is easier to explain and passes the test suite, I am happy to hear about it.

**Comment by RaduBerinde** [comment]
I understand, thanks.

I took a look and the cases that were covered by this check are cases where the delta alternated between `+/- eps` where `eps` is the last bit of precision. For example:

```
Z: (0.979795897113)  delta: (8.63616855509e-78)  zprec: 256 zexp: 0
Z: (0.979795897113)  delta: (-8.63616855509e-78)  zprec: 256 zexp: 0
Z: (0.979795897113)  delta: (8.63616855509e-78)  zprec: 256 zexp: 0
Z: (0.979795897113)  delta: (-8.63616855509e-78)  zprec: 256 zexp: 0
Z: (0.979795897113)  delta: (8.63616855509e-78)  zprec: 256 zexp: 0
```
`8.63616855509e-78` is ~`2^-256`

Another:
```
Z: (14142135623.7)  delta: (1.48368246027e-67)  zprec: 256 zexp: 34
Z: (14142135623.7)  delta: (-1.48368246027e-67)  zprec: 256 zexp: 34
Z: (14142135623.7)  delta: (1.48368246027e-67)  zprec: 256 zexp: 34
```
`1.48368246027e-67` is ~`2^-(256-34)`.

We can check if delta is smaller than this value, which makes sense conceptually: https://github.com/robpike/ivy/commit/7d424cdf6f25b091a3ca3b28016817fc256ed136

If you think this is better, I'll open a PR.

**Comment by robpike** [comment]
That sounds good. Thanks for investigating.

Before I can accept a PR from you, I will need to have you sign the Google CLA at https://cla.developers.google.com/about/google-individual. Sorry about that.

**Comment by RaduBerinde** [comment]
I already signed it (I contributed to `go` before), thanks.

**Comment by robpike** [comment]
I couldn't find your github address, but now I have found your email address, and indeed you are all set. Apologies for the false alarm.
