### ISSUE TITLE
Inconsistent constant value

### ISSUE THREAD

**Issue by suryaabhi** [robpike/ivy#38]
![img_0503](https://cloud.githubusercontent.com/assets/15243985/26593700/c1aaa448-4582-11e7-94d9-24f1eb527575.PNG)

In the attached image, the value of predefined constant "e" has been changed..

**Comment by robpike** [comment]
This was fixed some time in the "dev" branch. I have now rolled the latest fixes to master. How long that will take to get to the App Store I can't say.

Apologies for the bug.

**Comment by shurcooL** [comment]
@robpike, while ivy and the `dev` branch are fresh on your mind, could you please review (and merge, if they LGTY) two outstanding PRs at https://github.com/robpike/ivy/pulls?

I've personally reviewed both and they LGTM (but, I'm also the author of one of them).

**Comment by suryaabhi** [comment]
Glad to hear that!
