### ISSUE TITLE
Big Numbers require a huge screen

### ISSUE THREAD

**Issue by z505** [robpike/ivy#39]
It says "Prototype apps for iPhone, iPad, and Android"

Okay but I am working with the types of numbers that will fill up a 19 inch screen multiplied by hundreds of screens....

Are there any demos for: Mac laptops, Windows.

The big numbers will have trouble fitting on a cell phone screen. iPad indeed comes close since it is a 10 inch screen or so.

If there are no Windows/macOS compiled demos, I might just be the one to create one.

**Comment by shurcooL** [comment]
> Are there any demos for: Mac laptops, Windows.

Can you clarify what you mean by "demos", exactly?

ivy, as available in this repository, is just a command-line application. You can run it in any terminal on macOS, Linux, or Windows. You can maximize said terminal on a 4K or 5K monitor.

**Comment by robpike** [comment]
The phone demo is just a wrapping of the command-line one. Check out ivy from github, then cd robpike.io/ivy/demo type `go run demo.go`.

**Comment by z505** [comment]
shurcooL, likely by demo I mean where you can easily copy and paste numbers in a GUI environment, without the terminal getting in your way - in fact, as far as I researched, you even wrote a demo in HTML a while back which I recently found somewhere! I may expand on this html/css demo. The issue with a terminal compared to a proper GUI is it is simply much harder to expand upon and utilize efficiently : say I want to add a gui Button for commonly used maths.  

Calculators have buttons: you can "store" certain values in memory, as an example, then recall them later. Or calculators have buttons to show you functions you wouldn't remember otherwise. Doing this at a terminal still is possible, but... I prefer to have a GUI for some things.

Anyway, thanks for Ivy, I'm needing to work with some massive numbers right now :-)

I'll likely make my own HTML 5 /css demo, possibly based on shurcooL's code if that is in fact yours that I found.

I do not mean to reopen this issue: this is just a comment. It should go in a discussion forum rather than an issue: but, there is not likely one that exists for Ivy.

I did find a potential bug in Ivy where if you do something it causes the calculator to no longer work, I'll report this as a separate issue and give you a patch if I can resolve the bug myself! Seems like a clear cut case of it breaking when you do a large power operation, probably a error check will fix it.

**Comment by shurcooL** [comment]
> shurcooL, likely by demo I mean where you can easily copy and paste numbers in a GUI environment, without the terminal getting in your way.

I see. Isn't that usually referred to as an "application", "app", "program", or "GUI application", etc.? I haven't heard it called "demo" before. To me, "demo" means a demonstration. Either a trial version of a paid video game, or a demonstration of how something can be used.

> In fact, as far as I researched, you even wrote a demo in HTML a while back which I recently found somewhere!

Yes, I ported ivy to the browser at https://github.com/shurcooL/ivybrowser. The port is very [simple](https://github.com/shurcooL/ivybrowser/blob/51aad7aae4cb24b1491671eb5a187cbc0658b50f/io_js.go) and just creates a terminal-like environment in HTML, with a \<pre\> and \<input\> elements.

> I'll likely make my own HTML 5 /css demo, possibly based on shurcooL's code if that is in fact yours that I found.

Feel free!
