### ISSUE TITLE
Predefined functions can not be used as numerical values in higher bases

### ISSUE THREAD

**Issue by mirtchovski** [robpike/ivy#4]
This is on the android app.

```
> ) base 16

> abc + def
error: unexpected Def: "def"
> ) base 30

> abc + log
error: unexpecred Newline: "\n"
> abc + lpg
126s

> abc + defd
doqp
```

**Comment by robpike** [comment]
Documented:

    	If the base is greater than 10, any identifier formed from
    	valid numerals in the base system, such as abe for base 16,
    	is taken to be a number.

**Comment by mirtchovski** [comment]
I read that paragraph and according to it I expected "def" to be evaluated as "def" in base 16, not "expected [Identifier], got Newline".

```
> ) base 10

> def 
error: expected [Identifier], got Newline: "\n"
> dee
error: undefined variable "dee"
> dee = 10

> dee
10

> ) base 16

> def
error: expected [Identifier], got Newline: "\n"
> dee
dee
```

I expected "def" and "dee" to be treated equally.

**Comment by robpike** [comment]
def is a keyword, not an identifier, but you have a point. I will investigate.

**Comment by robpike** [comment]
The "def" keyword is indeed a keyword. I think the right fix is to make sure the keyword is not a valid hexadecimal number, so I'll do that: "op" is a good, maybe better choice.

Compatibility is not an issue here.

**Comment by mirtchovski** [comment]
but wouldn't you possibly run into the same issue at higher bases? from the original issue post, here's a clash between the "log" function and the valid number 'log₃₀' (21:24:16₃₀ according to wolfram alpha). "lpg" works file:

```
> ) base 30

> abc + log
error: unexpecred Newline: "\n"
> abc + lpg
126s
```

**Comment by robpike** [comment]
Yes, you will run into it at higher bases. At higher bases, more and more identifiers will disappear. Use upper case.

This is just a toy, remember.
