### ISSUE TITLE
Ivy Doc doesn't explain indexing operation '[ ]'

### ISSUE THREAD

**Issue by 9nut** [robpike/ivy#61]
Although there is an explanation of the indexing operation in demo.ivy, the doc only hints at it in the 'largest' op example.

**Comment by chenguohui49** [comment]
One thing that you can not have is the way 
[LICENSE.txt](https://github.com/robpike/ivy/files/4441113/LICENSE.txt)

**Comment by glxxyz** [comment]
Wasn't this fixed by https://github.com/robpike/ivy/commit/a0b4ddf4aab83b1a917ef13a1e914f41ed1c2764 ?

**Comment by robpike** [comment]
Yes, thanks.
