### ISSUE TITLE
Monadic Flip and rot destructrively modify their input, Matrix product

### ISSUE THREAD

**Issue by alexshendi** [robpike/ivy#63]
Hi,

The monadic 'flip' and 'rot' operators destructrively modify their input. That doesn't look right to me. The matrix product +.* only works for square matrices.

See attached session transcript:

term% ivy
a=(2,3) rho iota 6

b=(2,2) rho 4 -1 -1 4

c=(2,2) rho iota 4

a
1 2 3
4 5 6

b
 4 -1
-1  4

c
1 2
3 4

flip a
4 5 6
1 2 3

a
4 5 6
1 2 3

flip a
1 2 3
4 5 6

a
1 2 3
4 5 6

a +.* b
shape mismatch for inner product (2 3) times (2 2)

b +.* c
 1  4
11 14

b
 4 -1
-1  4

c
1 2
3 4

**Comment by robpike** [comment]
Thanks for the report. I tried to track down all the argument-overwriting operators but clearly missed a couple. Will fix.

**Comment by robpike** [comment]
P.S. You don't need to parenthesize the rank vector for rho.
2 3 rho iota 6
works fine because 2 3 is a single operand - a vector.

**Comment by robpike** [comment]
Ah, I did track all these down. This has been fixed in the dev branch. I need to update master.
