### ISSUE TITLE
Working Recursive Function

### ISSUE THREAD

**Issue by jojomoore2007** [robpike/ivy#65]
Just thought you might want to see this:

```
op recursive x =
ivy (((x==0) sel '__=0'),((x==1) sel '__=1'),((x>=2) sel ('__=(recursive ',(text x-2),')+(recursive ',(text x-1),')')))
__

```

It uses the 'ivy' operator to run a command that sets '__' to a different type of value based on one of three conditions:

1. if x==0, run `__=0`
2. if x==1, run `__=1`
3. if x>=2, run `__=(recursive x-2)+(recursive x-1)` (`x-2` and `x-1` are calculated first, then converted to text format and added to the string)

If you haven't noticed yet, this is a recursive implementation of the Fibonacci Sequence.
The command selector utilizes two properties I noticed in the 'sel' operator:

- (0 sel x) is an empty vector
- (1 sel x) is equivalent to x

The only other thing you need to do is concatenate the strings and execute the result. The output value gets stored in __, which can then easily be returned by the function.

**Comment by robpike** [comment]
That is insane. Well done.

I really should do something to make control flow easier.

**Comment by glxxyz** [comment]
Dyalog APL's [dfns](https://help.dyalog.com/18.0/#Language/Defined%20Functions%20and%20Operators/DynamicFunctions/Dynamic%20Functions%20and%20Operators.htm) have [Guards](https://help.dyalog.com/18.0/#Language/Defined%20Functions%20and%20Operators/DynamicFunctions/Guards.htm) with short-circuit evaluation, could user defined functions support something like this?
```
op fib x =
 x==0: 0
 x==1: 1
 (fib x-1) + fib x-2
```

**Comment by tcolgate** [comment]
This is a really elegant feature. The Decomposable interface in the implementation is an interesting approach I'd never have considered.

**Comment by robpike** [comment]
Thanks, but know it's just a hack to break isolation. Also, if I were starting ivy over I might do a different package layout; the import graph is hard to keep from going circular. Everything ends up in package value.

**Comment by glxxyz** [comment]
That's amazing, I was just brainstorming. Very clean implementation too. Thanks!
