### ISSUE TITLE
Running "ivy" with empty vectors...

### ISSUE THREAD

**Issue by jojomoore2007** [robpike/ivy#66]
The 'ivy' operation returns the result of a given expression. This is usually perfectly fine, but becomes an issue when given an empty vector:
```
ivy ''
```
The above code returns `nil`. Not a vector, or a number. Just `nil`. This isn't enough to crash ivy on its own. However, when attempting to use it in an operation... things break. Attempting to run `ivy ivy ''` will cause Go to fully crash, returning the following error:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x503e46]

goroutine 1 [running]:
robpike.io/ivy/run.Run.func1(0x623ba0, 0xc4200ee000, 0xc42004fd01, 0x57a340, 0xc42009a008, 0xc42004fe48)
	/home/joey/go/src/robpike.io/ivy/run/run.go:58 +0x270
panic(0x532aa0, 0x61b3c0)
	/usr/lib/go-1.10/src/runtime/panic.go:502 +0x229
robpike.io/ivy/parse.(*unary).Eval(0xc42008c2a0, 0x57ae20, 0xc42009f0e0, 0x499607, 0xc4200f4000)
	/home/joey/go/src/robpike.io/ivy/parse/parse.go:186 +0x56
robpike.io/ivy/exec.(*Context).Eval(0xc42009f0e0, 0xc420082370, 0x1, 0x1, 0x1, 0x0, 0x0)
	/home/joey/go/src/robpike.io/ivy/exec/context.go:116 +0xa1
robpike.io/ivy/run.Run(0xc4200ee000, 0x57ae20, 0xc42009f0e0, 0xc4200ea001, 0x1000)
	/home/joey/go/src/robpike.io/ivy/run/run.go:69 +0x1a1
main.main()
	/home/joey/go/src/robpike.io/ivy/ivy.go:101 +0x584
```

As far as I can tell, the same problem occurs when `ivy ''` is passed as an argument to *any* operation.

Possible fixes:

- Make `ivy x` return the text result of an expression
    - Possibly also create a `val x` (or `value x`) operation that returns the actual value of an expression
- Remove `ivy x`
- Change `nil` values to empty vectors

**Comment by robpike** [comment]
This one seems to be just a bug, a missing nil check in run/eval. The fix is obvious.
If you think there's a deeper problem, let me know.

**Comment by robpike** [comment]
That fix has other problems.
Thinking.

**Comment by robpike** [comment]
Changed in [\072b8a](https://github.com/robpike/ivy/commit/04bfaf6224c8e8d59306a04753719f0881072b8a) to return an empty vector.
