### ISSUE TITLE
inverted arithmetic in matrix op vector

### ISSUE THREAD

**Issue by rsc** [robpike/ivy#70]
Been staring at this for a while and I think it must be a bug.
A surprising one, but either that or I've missed something quite fundamental.

```
(2 2 rho 2 3 5 7) / (11 13)
11/2 13/3
11/5 13/7
```

**Comment by robpike** [comment]
Very nice. Obviously upside down but I think the real error is trying to evaluate it at all. The ranks are mismatched. Even dyalog doesn't handle it.

So I've missed something fundamental. What did you expect to happen? (Other than numerator and denominator the right way around.)

**Comment by robpike** [comment]
But I notice that + for example "works" in ivy but not in dyalog. Interesting. Will investigate.

**Comment by robpike** [comment]
Spectacular failure. Thanks for reporting it.
