### ISSUE TITLE
locals vs globals is unclear and can change unexpectedly

### ISSUE THREAD

**Issue by rsc** [robpike/ivy#82]
What does the variable name x mean in a function (user-defined operator) body?
Right now the rule in function f is:
(1) if x is the name of one of f's argument, then x refers to that local variable.
(2) if x is the name of a global, then x refers to that global.
(3) otherwise, x refers to a local variable (possibly not yet created).

I sent PR #81 to fix a bug where Ivy wasn't respecting these rules (a definite bug fix),
but I wonder whether the rules should be changed anyway.
Consider some function that uses (intended as local) variables in its implementation,
like this not-very-good Fibonacci function:

```
% ivy
op fib n =
	n <= 1: n
	a = fib n-1
	b = fib n-2
	a + b


fib 10
55
```

Now suppose that is loaded from a library and we don't know how its implemented.
And we are playing around:

```
% ivy -f fib.ivy
fib 10
55

a
undefined variable "a"

a = 1

fib 10
5
```

Creating the global named 'a' changes the meaning of the fib function:
what used to be a local variable becomes a global variable.
This means that functions using local variables aren't robust
against the creation of globals that happen to use the same names.
I think probably something should be done about that.

Python has this problem too, and solves it by saying that the first
use of a variable in the function determines what it is.
If the first use is a write, then the name refers to a new local.
If the first use is a read, then the name can refer to a global.
If you want to override this, the special statement 'global x'
forces the name to refer to a global. 
Use is not strictly in writing-code order: x = x+1 reads x before writing it,
so it refers to a global if one exists.
Ivy could adopt this rule too, but in Python, I have a hard time remembering it,
and while it usually does the right thing, it's mysterious when it doesn't.
Definitely one option though.

Another option would be to require saying 'global x' any time you
want to refer to a global. That would be easier to remember at least.
but maybe a bit too annoying.

A third option would be, in a nod to Go's export rule, to say that
inside functions, capitalized variables are always globals,
while lowercase variables are always locals.
This would make it very clear at all mentions of a variable
whether it was private to the function or not.
You could still manipulate lowercase globals in the interactive loop,
but those would not be available to functions.
Lowercase globals would essentially be the local variables for the interactive loop.

Not sure what the right answer is here.

**Comment by robpike** [comment]
I kinda like python's rule: new writes are local, reads can be global. But then I'm not sure what "first" should be. What is
a = a ?

And  I'd like to avoid more special words.

Need to think more.

**Comment by rsc** [comment]
After discovering the walk in parse.references (because I'd broken it with the new index code), which is almost exactly what you need for the read/write analysis, I implemented the Python approach. There's no special word needed. You can start a function with one of:

    x  # x is global
    _ = x # x is global

Of course even that's not necessary at all unless the function is writing blindly to x, without reading it.

The commit is https://github.com/rsc/ivy/commit/25e84e22d79f70daa8b53171614917c543cf7dcf if anyone wants to take a look. The stack changed to be a simple []value.Value, instead of a slice of maps, indexing backward from the end to get at the current function's variables. That was not strictly necessary but fell out easily.

I haven't made it a PR, both because the approach is not decided and because it depends on the )save fix PR, and that seemed too confusing to have the )save fix commit appear in two different PRs.
