### ISSUE TITLE
vector-indexed indexing and assignment don't generalize

### ISSUE THREAD

**Issue by rsc** [robpike/ivy#85]
Consider:

	% ivy
	x = 3 4 rho iota 9

	x[2][2 3]
	6 7

This works fine today. But now consider

	x[2 3]
	5 6 7 8
	9 1 2 3

	x[2 3][1 4]
	index 4 out of range (shape (2 4))

	y=x[2 3]; y[1 4]
	index 4 out of range (shape (2 4))

Here, x[2 3][1 4] is being treated the same as the y= version,
just without the y.

There is no way in Ivy today to extract a sub-shape of a matrix,
what in APL would be x[2 3; 1 4].

I started working on making vector-indexed assignment work,
so that things like APL's (from tryapl.org):

	      x ← 3 4 ⍴⍳9
	      x[2 3; 1 4] ← 0
	      x
	1 2 3 4
	0 6 7 0
	0 1 2 0

or

	      x ← 3 4 ⍴⍳12
	      x[2 3; 1 4] ← -2 2 ⍴⍳4
	      x
	 1  2  3  4
	¯1  6  7 ¯2
	¯3 10 11 ¯4

would work. Those both work (in Ivy syntax) in my copy now,
but then I noticed that x[2 3][1 4] = x[2 3][1 4] does not,
because x[2 3][1 4] didn't mean what I expected it to.

I see three possible options:

1. Do nothing, just don't provide that functionality.

2. Switch to ; for separating indexes, like APL.

3. Define that x[i][j][k] is processing 3 dimensions of x, not ((x[i])[j])[k]. Perhaps code that wants the latter interpretation can add parens.

Perhaps there are more.

**Comment by robpike** [comment]
I've been thinking that array indexing should probably use semicolons for some time now. But it's tricky because, by a piece of magic, [ can be treated as a binary operator, but then what is 1 2; 3 4? It's not an expression.

**Comment by rsc** [comment]
Sent PR #86, which does both the syntax change and the implementation of rectangle assignment.
