### ISSUE TITLE
unary rho with a non-vector returns nothing

### ISSUE THREAD

**Issue by db47h** [robpike/ivy#9]
Note that this is on the dev branch. Example:

    rho 4

nothing returned.

    rho 4 5
    2

Shouldn't `rho 4` to return 1 ?

**Comment by robpike** [comment]
4 is a scalar, so it has no dimension. Its shape is null.

rho 1 rho 4 

gives 1 because 1 rho 4 is a 1-element vector.

**Comment by db47h** [comment]
Makes sense, thanks for the clarification. The fact that some binary operators internally cast scalars to single element vectors got me confused.
