### ISSUE TITLE
Possible base 1 log issue

### ISSUE THREAD

**Issue by glxxyz** [robpike/ivy#97]
Base 1 logs give results that I didn't expect. I compared with a couple of other sources:

```
              Ivy        tryapl.org      WolframAlpha
          -----------  -------------   ----------------
1 log .5 |    -Inf      DOMAIN ERROR   complex infinity
         |
1 log 1  |    0         1              (undefined)
         |
1 log 2  |    +Inf      DOMAIN ERROR   complex infinity
```

Perhaps all three should report a base error?

**Comment by robpike** [comment]
The answers seem reasonable to me. There are other valid interpretations of logs base 1, but ivy's is as reasonable as the others.

**Comment by rsc** [comment]
I agree about these being reasonable answers.
