### ISSUE TITLE
Infinity crashes / hangs

### ISSUE THREAD

**Issue by glxxyz** [robpike/ivy#98]
In #97 there's a way to return infinity but there may be other ways. Is it expected to have an infinity float within Ivy? Many operations work correctly, with some exceptions:

```
1 log 2
+Inf

# Exits with stack trace
(1 log 2) - 1 log 2
panic: subtraction of infinities with equal signs

# Hangs, same for 'cos' and 'tan'
sin 1 log 2
```

There are similar issues with `+`,  `/`, unary `**`,  `cos`, and `tan`. Some others such as `log` and binary `**` don't converge.

**Comment by robpike** [comment]
Good question. I haven't thought about infinities and other funny values like negative zero; I've just called math/big and handed back the result. But it's worth doing, and that panic isn't good.

**Comment by robpike** [comment]
Note to self: math/big exports ErrNan, and could recognize it.
